import type { Metadata } from "next";
import { Anuphan as FontSans, Geist_Mono as FontMono } from "next/font/google";
import "./globals.css";
import { Provider } from "@/app/provider";

const fontSans = FontSans({
  variable: "--font-sans",
  subsets: ["thai"],
});

const fontMono = FontMono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontSans.variable} ${fontMono.variable} antialiased font-sans`}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
